// src/lib/data.ts
export const siteConfig = {
  name: "Vivo",
  tagline: "Elevated Living. Urban Energy.",
  address: "13255 104 Ave, Surrey, BC",
  city: "Surrey, BC",
  postalCode: "V3T 0H6",
  phone: "(604) 555-0182",
  email: "leasing@vivoliving.ca",
  leasingHours: [
    { days: "Monday – Friday", hours: "9:00 AM – 6:00 PM" },
    { days: "Saturday", hours: "10:00 AM – 5:00 PM" },
    { days: "Sunday", hours: "By Appointment" },
  ],
  social: {
    instagram: "#",
    facebook: "#",
    twitter: "#",
  },
  meta: {
    title: "Vivo | Rental Homes in Surrey City Centre",
    description:
      "Discover modern 1, 2 & 3 bedroom rental homes at Vivo — purpose-built living in the heart of Surrey City Centre. Book a tour today.",
    ogImage: "/images/og-image.jpg",
  },
};

// Image previews generated from PDFs — regenerate with: node scripts/pdf-to-images.mjs
export const floorPlans = [
  // ── Studios ──────────────────────────────────────────────────────
  {
    id: "STUDIO-A",
    name: "Studio A",
    type: "Studio",
    bedrooms: 0,
    bathrooms: 1,
    sqftInterior: 416,
    sqftExterior: 62,
    sqft: 478,
    pdf: "/unit/STUDIO-A.pdf",
    image: "/unit/images/STUDIO-A.png",
    features: ["Balcony", "In-suite Laundry", "Open Layout"],
  },
  {
    id: "STUDIO-B",
    name: "Studio B",
    type: "Studio",
    bedrooms: 0,
    bathrooms: 1,
    sqftInterior: 346,
    sqftExterior: 91,
    sqft: 437,
    pdf: "/unit/STUDIO-B.pdf",
    image: "/unit/images/STUDIO-B.png",
    features: ["Balcony", "In-suite Laundry", "Open Layout"],
  },

  // ── One Bedroom ───────────────────────────────────────────────────
  {
    id: "1B-E1",
    name: "Plan E1",
    type: "1 Bed",
    bedrooms: 1,
    bathrooms: 1,
    sqftInterior: 493,
    sqftExterior: 61,
    sqft: 554,
    pdf: "/unit/1B-E1.pdf",
    image: "/unit/images/1B-E1.png",
    features: ["Balcony", "In-suite Laundry"],
  },
  {
    id: "1B-E2",
    name: "Plan E2",
    type: "1 Bed",
    bedrooms: 1,
    bathrooms: 1,
    sqftInterior: 520,
    sqftExterior: 60,
    sqft: 580,
    pdf: "/unit/1B-E2.pdf",
    image: "/unit/images/1B-E2.png",
    features: ["Balcony", "In-suite Laundry"],
  },
  {
    id: "1B-F",
    name: "Plan F",
    type: "1 Bed",
    bedrooms: 1,
    bathrooms: 1,
    sqftInterior: 581,
    sqftExterior: 90,
    sqft: 671,
    pdf: "/unit/1B-F.pdf",
    image: "/unit/images/1B-F.png",
    features: ["Balcony", "In-suite Laundry"],
  },
  {
    id: "1B-G1",
    name: "Plan G1",
    type: "1 Bed",
    bedrooms: 1,
    bathrooms: 1,
    sqftInterior: 615,
    sqftExterior: 92,
    sqft: 706,
    pdf: "/unit/1B-G1.pdf",
    image: "/unit/images/1B-G1.png",
    features: ["Balcony", "In-suite Laundry"],
  },
  {
    id: "1B-H1",
    name: "Plan H1",
    type: "1 Bed",
    bedrooms: 1,
    bathrooms: 1,
    sqftInterior: 510,
    sqftExterior: 64,
    sqft: 574,
    pdf: "/unit/1B-H1.pdf",
    image: "/unit/images/1B-H1.png",
    features: ["Balcony", "In-suite Laundry"],
  },
  {
    id: "1B-X",
    name: "Plan X",
    type: "1 Bed",
    bedrooms: 1,
    bathrooms: 1,
    sqftInterior: 440,
    sqftExterior: 92,
    sqft: 532,
    pdf: "/unit/1B-X.pdf",
    image: "/unit/images/1B-X.png",
    features: ["Balcony", "In-suite Laundry"],
  },
  {
    id: "1B-Y",
    name: "Plan Y",
    type: "1 Bed",
    bedrooms: 1,
    bathrooms: 1,
    sqftInterior: 571,
    sqftExterior: 154,
    sqft: 725,
    pdf: "/unit/1B-Y.pdf",
    image: "/unit/images/1B-Y.png",
    features: ["Large Balcony", "In-suite Laundry"],
  },

  // ── One Bedroom + Den ─────────────────────────────────────────────
  {
    id: "1BD-C1",
    name: "Plan C1",
    type: "1 Bed + Den",
    bedrooms: 1,
    bathrooms: 1,
    sqftInterior: 591,
    sqftExterior: 52,
    sqft: 643,
    pdf: "/unit/1BD-C1.pdf",
    image: "/unit/images/1BD-C1.png",
    features: ["Balcony", "Den", "In-suite Laundry"],
  },
  {
    id: "1BD-C2",
    name: "Plan C2",
    type: "1 Bed + Den",
    bedrooms: 1,
    bathrooms: 1,
    sqftInterior: 543,
    sqftExterior: 51,
    sqft: 594,
    pdf: "/unit/1BD-C2.pdf",
    image: "/unit/images/1BD-C2.png",
    features: ["Balcony", "Den", "In-suite Laundry"],
  },
  {
    id: "1BD-G2",
    name: "Plan G2",
    type: "1 Bed + Den",
    bedrooms: 1,
    bathrooms: 1,
    sqftInterior: 591,
    sqftExterior: 93,
    sqft: 683,
    pdf: "/unit/1BD-G2.pdf",
    image: "/unit/images/1BD-G2.png",
    features: ["Balcony", "Den", "In-suite Laundry"],
  },
  {
    id: "1BD-K",
    name: "Plan K",
    type: "1 Bed + Den",
    bedrooms: 1,
    bathrooms: 1,
    sqftInterior: 700,
    sqftExterior: 51,
    sqft: 751,
    pdf: "/unit/1BD-K.pdf",
    image: "/unit/images/1BD-K.png",
    features: ["Balcony", "Den", "In-suite Laundry", "Accessible Unit"],
  },

  // ── Two Bedroom ───────────────────────────────────────────────────
  {
    id: "2B-M1-M2",
    name: "Plan M1 / M2",
    type: "2 Bed",
    bedrooms: 2,
    bathrooms: 2,
    sqftInterior: 781,
    sqftExterior: 97,
    sqft: 878,
    pdf: "/unit/2B-M1-M2.pdf",
    image: "/unit/images/2B-M1-M2.png",
    features: ["Balcony", "In-suite Laundry", "2 Full Baths"],
  },
  {
    id: "2B-M3",
    name: "Plan M3",
    type: "2 Bed",
    bedrooms: 2,
    bathrooms: 2,
    sqftInterior: 819,
    sqftExterior: 52,
    sqft: 871,
    pdf: "/unit/2B-M3.pdf",
    image: "/unit/images/2B-M3.png",
    features: ["Balcony", "In-suite Laundry", "2 Full Baths"],
  },
  {
    id: "2B-N",
    name: "Plan N",
    type: "2 Bed",
    bedrooms: 2,
    bathrooms: 2,
    sqftInterior: 675,
    sqftExterior: 58,
    sqft: 733,
    pdf: "/unit/2B-N.pdf",
    image: "/unit/images/2B-N.png",
    features: ["Balcony", "In-suite Laundry", "2 Full Baths"],
  },
  {
    id: "2B-O",
    name: "Plan O",
    type: "2 Bed",
    bedrooms: 2,
    bathrooms: 2,
    sqftInterior: 792,
    sqftExterior: 66,
    sqft: 858,
    pdf: "/unit/2B-O.pdf",
    image: "/unit/images/2B-O.png",
    features: ["Balcony", "In-suite Laundry", "2 Full Baths"],
  },
  {
    id: "2B-P",
    name: "Plan P",
    type: "2 Bed",
    bedrooms: 2,
    bathrooms: 2,
    sqftInterior: 707,
    sqftExterior: 56,
    sqft: 763,
    pdf: "/unit/2B-P.pdf",
    image: "/unit/images/2B-P.png",
    features: ["Balcony", "In-suite Laundry", "2 Full Baths"],
  },
  {
    id: "2B-Q",
    name: "Plan Q",
    type: "2 Bed",
    bedrooms: 2,
    bathrooms: 2,
    sqftInterior: 740,
    sqftExterior: 62,
    sqft: 802,
    pdf: "/unit/2B-Q.pdf",
    image: "/unit/images/2B-Q.png",
    features: ["Balcony", "In-suite Laundry", "2 Full Baths"],
  },
  {
    id: "2B-R1",
    name: "Plan R1",
    type: "2 Bed",
    bedrooms: 2,
    bathrooms: 2,
    sqftInterior: 742,
    sqftExterior: 71,
    sqft: 813,
    pdf: "/unit/2B-R1.pdf",
    image: "/unit/images/2B-R1.png",
    features: ["Balcony", "In-suite Laundry", "2 Full Baths"],
  },
  {
    id: "2B-S",
    name: "Plan S",
    type: "2 Bed",
    bedrooms: 2,
    bathrooms: 2,
    sqftInterior: 745,
    sqftExterior: 71,
    sqft: 816,
    pdf: "/unit/2B-S.pdf",
    image: "/unit/images/2B-S.png",
    features: ["Balcony", "In-suite Laundry", "2 Full Baths"],
  },
  {
    id: "2B-U",
    name: "Plan U",
    type: "2 Bed",
    bedrooms: 2,
    bathrooms: 2,
    sqftInterior: 810,
    sqftExterior: 93,
    sqft: 903,
    pdf: "/unit/2B-U.pdf",
    image: "/unit/images/2B-U.png",
    features: ["Balcony", "In-suite Laundry", "2 Full Baths"],
  },

  // ── Two Bedroom + Den ─────────────────────────────────────────────
  {
    id: "2BD-D",
    name: "Plan D",
    type: "2 Bed + Den",
    bedrooms: 2,
    bathrooms: 2,
    sqftInterior: 1086,
    sqftExterior: 53,
    sqft: 1139,
    pdf: "/unit/2BD-D.pdf",
    image: "/unit/images/2BD-D.png",
    features: ["Balcony", "Den", "In-suite Laundry", "2 Full Baths", "Accessible Unit"],
  },
  {
    id: "2BD-T1",
    name: "Plan T1",
    type: "2 Bed + Den",
    bedrooms: 2,
    bathrooms: 2,
    sqftInterior: 890,
    sqftExterior: 139,
    sqft: 1029,
    pdf: "/unit/2BD-T1.pdf",
    image: "/unit/images/2BD-T1.png",
    features: ["Large Balcony", "Den", "In-suite Laundry", "2 Full Baths"],
  },
  {
    id: "2BD-T2",
    name: "Plan T2",
    type: "2 Bed + Den",
    bedrooms: 2,
    bathrooms: 2,
    sqftInterior: 883,
    sqftExterior: 60,
    sqft: 943,
    pdf: "/unit/2BD-T2.pdf",
    image: "/unit/images/2BD-T2.png",
    features: ["Balcony", "Den", "In-suite Laundry", "2 Full Baths"],
  },

  // ── Three Bedroom ─────────────────────────────────────────────────
  {
    id: "3B-W",
    name: "Plan W",
    type: "3 Bed",
    bedrooms: 3,
    bathrooms: 2,
    sqftInterior: 923,
    sqftExterior: 76,
    sqft: 999,
    pdf: "/unit/3B-W.pdf",
    image: "/unit/images/3B-W.png",
    features: ["Balcony", "In-suite Laundry", "2 Full Baths"],
  },
];

export const amenities = {
  building: [
    {
      id: "gym",
      icon: "dumbbell",
      title: "Fitness Centre",
      description: "A fully equipped fitness studio with cardio machines, free weights, and dedicated stretching space.",
    },
    {
      id: "lounge",
      icon: "sofa",
      title: "Resident Lounge",
      description: "A beautifully appointed common room for relaxing, working from home, or entertaining guests.",
    },
    {
      id: "rooftop",
      icon: "sun",
      title: "Rooftop Terrace",
      description: "Take in panoramic views of Surrey and the North Shore mountains from our landscaped rooftop terrace.",
    },
    {
      id: "concierge",
      icon: "shield",
      title: "Secure Entry",
      description: "Key-fob access and intercom throughout the building for your safety and peace of mind.",
    },
    {
      id: "bike",
      icon: "bicycle",
      title: "Bike Storage & Repair",
      description: "Dedicated secure bike storage with a repair station — perfect for the urban commuter.",
    },
    {
      id: "parking",
      icon: "car",
      title: "Underground Parking",
      description: "Available underground parking stalls with EV charging rough-in for select units.",
    },
    {
      id: "pets",
      icon: "heart",
      title: "Pet-Friendly",
      description: "Dogs and cats welcome. Enjoy convenient access to nearby parks and green spaces.",
    },
    {
      id: "parcel",
      icon: "package",
      title: "Smart Parcel Lockers",
      description: "Automated parcel storage so you never miss a delivery, available 24/7.",
    },
  ],
  inSuite: [
    {
      id: "laundry",
      icon: "washing-machine",
      title: "In-Suite Laundry",
      description: "Full-size washer and dryer in every home.",
    },
    {
      id: "appliances",
      icon: "chef-hat",
      title: "Premium Appliances",
      description: "Stainless steel kitchen appliances including fridge, stove, dishwasher, and microwave.",
    },
    {
      id: "finishes",
      icon: "sparkles",
      title: "Quality Finishes",
      description: "Wide-plank flooring, stone countertops, and designer fixtures throughout.",
    },
    {
      id: "balcony",
      icon: "wind",
      title: "Private Balconies",
      description: "Most suites feature private balconies with sweeping views of the city and mountains.",
    },
    {
      id: "windows",
      icon: "sun",
      title: "Floor-to-Ceiling Windows",
      description: "Expansive windows flood every room with natural light.",
    },
    {
      id: "ac",
      icon: "thermometer",
      title: "Air Conditioning",
      description: "In-suite air conditioning keeps you comfortable year-round.",
    },
  ],
};

export const faqs = [
  {
    question: "What unit types are available at Vivo?",
    answer:
      "Vivo offers 1-bedroom, 2-bedroom, and 3-bedroom rental homes across 115 suites. Each suite features modern finishes, in-suite laundry, and most include private balconies.",
  },
  {
    question: "Are pets allowed?",
    answer:
      "Yes, Vivo is a pet-friendly community. Dogs and cats are welcome with reasonable size and breed restrictions. Please contact our leasing team for details.",
  },
  {
    question: "Is parking available?",
    answer:
      "Underground parking is available for an additional monthly fee. EV charging rough-in is available for select stalls. Contact leasing for current availability and pricing.",
  },
  {
    question: "When can I move in?",
    answer:
      "Some suites are available immediately. Others have upcoming availability. Visit our Floor Plans page for current availability or contact our leasing team directly.",
  },
  {
    question: "How do I book a tour?",
    answer:
      "You can book a tour online through our Contact page, call us at (604) 555-0182, or email leasing@vivoliving.ca. Our leasing team is available Monday–Friday 9AM–6PM, Saturday 10AM–5PM, and Sunday by appointment.",
  },
  {
    question: "What is included in the rent?",
    answer:
      "Rent includes use of all building amenities. Utilities (electricity, gas, water) are typically separate unless otherwise specified. Ask our leasing team about specific suite inclusions.",
  },
  {
    question: "Is Vivo close to public transit?",
    answer:
      "Vivo is located steps from the Central City SkyTrain Station, providing direct access to downtown Vancouver in under 45 minutes. Multiple bus routes also serve the area.",
  },
  {
    question: "What is the lease term?",
    answer:
      "Standard lease terms are 12 months. Shorter-term options may be available — please contact our leasing office to discuss your specific needs.",
  },
];

export const galleryItems = [
  { id: 1, category: "Exterior", src: "/images/gallery/exterior-1.jpg", alt: "Vivo building exterior" },
  { id: 2, category: "Exterior", src: "/images/gallery/exterior-2.jpg", alt: "Vivo entrance" },
  { id: 3, category: "Lobby", src: "/images/gallery/lobby-1.jpg", alt: "Vivo lobby" },
  { id: 4, category: "Lobby", src: "/images/gallery/lobby-2.jpg", alt: "Resident lounge" },
  { id: 5, category: "Suites", src: "/images/gallery/suite-1.jpg", alt: "Living room" },
  { id: 6, category: "Suites", src: "/images/gallery/suite-2.jpg", alt: "Kitchen" },
  { id: 7, category: "Suites", src: "/images/gallery/suite-3.jpg", alt: "Master bedroom" },
  { id: 8, category: "Suites", src: "/images/gallery/suite-4.jpg", alt: "Bathroom" },
  { id: 9, category: "Amenities", src: "/images/gallery/amenity-1.jpg", alt: "Fitness centre" },
  { id: 10, category: "Amenities", src: "/images/gallery/amenity-2.jpg", alt: "Rooftop terrace" },
  { id: 11, category: "Neighbourhood", src: "/images/gallery/neighbourhood-1.jpg", alt: "Surrey City Centre" },
  { id: 12, category: "Neighbourhood", src: "/images/gallery/neighbourhood-2.jpg", alt: "Central City Station" },
];

export const neighbourhoodItems = [
  {
    category: "Transit",
    icon: "train",
    items: ["Central City SkyTrain (5 min walk)", "Multiple bus routes", "45 min to Downtown Vancouver", "Easy highway access"],
  },
  {
    category: "Shopping",
    icon: "shopping-bag",
    items: ["Central City Mall", "Central City Shopping Centre", "Walmart & Canadian Tire nearby", "Farmer's Market (seasonal)"],
  },
  {
    category: "Dining",
    icon: "utensils",
    items: ["Holland Park area restaurants", "Local cafés and bakeries", "International cuisine nearby", "Quick-service & fine dining"],
  },
  {
    category: "Parks",
    icon: "tree",
    items: ["Holland Park (5 min walk)", "Green Timbers Urban Forest", "Bear Creek Park", "Tynehead Regional Park"],
  },
  {
    category: "Schools",
    icon: "book-open",
    items: ["KPU Surrey Campus", "SFU Surrey", "Kwantlen Polytechnic University", "Local elementary & secondary schools"],
  },
  {
    category: "Essentials",
    icon: "shopping-cart",
    items: ["Safeway & Save-On-Foods nearby", "Surrey Memorial Hospital", "Multiple pharmacies", "Banks & financial services"],
  },
];
